### ISSUE TITLE
If the kubelet working directory in the cluster is different，how to use node-driver-registrar

### ISSUE THREAD

**Issue by sys-liqian** [kubernetes-csi/node-driver-registrar#207]
in my kubernetes cluster
node1 kubelet woring dir is /var/lib/kubelet
node2 kubelet woring dir is /data/kubelet
how do i use node-driver-registrar

**Comment by mauriciopoppe** [comment]
Sorry for the late response, while we have these paths exposed as cli args I don't think we tested by having the kubelet working dir different to `/var/lib/kubelet`.

I'm not sure if the following will work:

```
      containers:
        - name: csi-driver-registrar
          image: k8s.gcr.io/sig-storage/csi-node-driver-registrar:v2.5.0
          args:
            - "--csi-address=/csi/csi.sock"
            - "--kubelet-registration-path=/var/lib/kubelet/plugins/<drivername.example.com>/csi.sock"
            - "--health-port=9809"
          volumeMounts:
            - name: plugin-dir
              mountPath: /csi
            - name: registration-dir
              mountPath: /registration
          ports:
            - containerPort: 9809
              name: healthz
          livenessProbe:
            httpGet:
              path: /healthz
              port: healthz
            initialDelaySeconds: 5
            timeoutSeconds: 5
      volumes:
        - name: registration-dir
          hostPath:
            path: /data/kubelet/plugins_registry/
            type: Directory
        - name: plugin-dir
          hostPath:
            path: /data/kubelet/plugins/<drivername.example.com>/
            type: DirectoryOrCreate
```
