### ISSUE TITLE
CSINode has no drivers

### ISSUE THREAD

**Issue by kickthemooon** [kubernetes-csi/node-driver-registrar#218]
I am trying to get aws-ebs-csi-driver running on Kubernetes EKS 1.23

CSINode resources are created for nodes created after the driver was installed but are missing drivers.

This is a node `/var/lib/kubelet` example:

![kubelet](https://i.imgur.com/o1KZWdi.png)

The node-csi-driver image is:
`k8s.gcr.io/sig-storage/csi-node-driver-registrar:v2.5.1`

node-csi-driver logs:
```
I0914 09:25:02.003172       1 main.go:166] Version: v2.5.1
I0914 09:25:02.003206       1 main.go:167] Running node-driver-registrar in mode=registration
I0914 09:25:02.003610       1 main.go:191] Attempting to open a gRPC connection with: "/csi/csi.sock"
I0914 09:25:04.066382       1 main.go:198] Calling CSI driver to discover driver name
I0914 09:25:04.068067       1 main.go:208] CSI driver name: "ebs.csi.aws.com"
I0914 09:25:04.068097       1 node_register.go:53] Starting Registration Server at: /registration/ebs.csi.aws.com-reg.sock
I0914 09:25:04.068253       1 node_register.go:62] Registration Server started at: /registration/ebs.csi.aws.com-reg.sock
I0914 09:25:04.068339       1 node_register.go:92] Skipping HTTP server because endpoint is set to: ""
```

The ebs-plugin image is:
`public.ecr.aws/ebs-csi-driver/aws-ebs-csi-driver:v1.11.2`

ebs-plugin node logs:
```
I0914 09:25:00.785711       1 node.go:98] regionFromSession Node service
I0914 09:25:00.785739       1 metadata.go:85] retrieving instance data from ec2 metadata
W0914 09:25:03.888576       1 metadata.go:88] ec2 metadata is not available
I0914 09:25:03.888590       1 metadata.go:96] retrieving instance data from kubernetes api
I0914 09:25:03.889324       1 metadata.go:101] kubernetes api is available
```

How can I further debug this?
Why are CSINode resources not created for existing nodes?
Is rolling of nodes necessary?

**Comment by mauriciopoppe** [comment]
Could you please share the yaml for the node component of the EBS CSI Driver?

**Comment by kickthemooon** [comment]
@mauriciopoppe 
```
apiVersion: v1
kind: Pod
metadata:
  annotations:
    kubernetes.io/psp: eks.privileged
  labels:
    app: ebs-csi-node
    app.kubernetes.io/component: csi-driver
    app.kubernetes.io/instance: aws-ebs-csi-driver
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: aws-ebs-csi-driver
    app.kubernetes.io/version: 1.11.2
    controller-revision-hash: 6fddb6889
    helm.sh/chart: aws-ebs-csi-driver-2.10.1
    pod-template-generation: "1"
  name: ebs-csi-node-25wvz
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchFields:
          - key: metadata.name
            operator: In
            values:
            - xxxxxx.xxxxxx.compute.internal
  containers:
  - args:
    - node
    - --endpoint=$(CSI_ENDPOINT)
    - --logtostderr
    - --v=2
    env:
    - name: CSI_ENDPOINT
      value: unix:/csi/csi.sock
    - name: CSI_NODE_NAME
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: spec.nodeName
    image: public.ecr.aws/ebs-csi-driver/aws-ebs-csi-driver:v1.11.2
    imagePullPolicy: IfNotPresent
    livenessProbe:
      failureThreshold: 5
      httpGet:
        path: /healthz
        port: healthz
        scheme: HTTP
      initialDelaySeconds: 10
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 3
    name: ebs-plugin
    ports:
    - containerPort: 9808
      name: healthz
      protocol: TCP
    resources: {}
    securityContext:
      privileged: true
      readOnlyRootFilesystem: true
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/lib/kubelet
      mountPropagation: Bidirectional
      name: kubelet-dir
    - mountPath: /csi
      name: plugin-dir
    - mountPath: /dev
      name: device-dir
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-n5zff
      readOnly: true
  - args:
    - --csi-address=$(ADDRESS)
    - --kubelet-registration-path=$(DRIVER_REG_SOCK_PATH)
    - --v=2
    env:
    - name: ADDRESS
      value: /csi/csi.sock
    - name: DRIVER_REG_SOCK_PATH
      value: /var/lib/kubelet/plugins/ebs.csi.aws.com/csi.sock
    image: k8s.gcr.io/sig-storage/csi-node-driver-registrar:v2.5.1
    imagePullPolicy: IfNotPresent
    name: node-driver-registrar
    resources: {}
    securityContext:
      allowPrivilegeEscalation: false
      readOnlyRootFilesystem: true
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /csi
      name: plugin-dir
    - mountPath: /registration
      name: registration-dir
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-n5zff
      readOnly: true
  - args:
    - --csi-address=/csi/csi.sock
    image: k8s.gcr.io/sig-storage/livenessprobe:v2.6.0
    imagePullPolicy: IfNotPresent
    name: liveness-probe
    resources: {}
    securityContext:
      allowPrivilegeEscalation: false
      readOnlyRootFilesystem: true
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /csi
      name: plugin-dir
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-n5zff
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeSelector:
    kubernetes.io/os: linux
  preemptionPolicy: PreemptLowerPriority
  priorityClassName: system-node-critical
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext:
    fsGroup: 0
    runAsGroup: 0
    runAsNonRoot: false
    runAsUser: 0
  serviceAccountName: ebs-csi-node-sa
  terminationGracePeriodSeconds: 30
  tolerations:
  - operator: Exists
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
  - effect: NoSchedule
    key: node.kubernetes.io/disk-pressure
    operator: Exists
  - effect: NoSchedule
    key: node.kubernetes.io/memory-pressure
    operator: Exists
  - effect: NoSchedule
    key: node.kubernetes.io/pid-pressure
    operator: Exists
  - effect: NoSchedule
    key: node.kubernetes.io/unschedulable
    operator: Exists
  volumes:
  - hostPath:
      path: /var/lib/kubelet
      type: Directory
    name: kubelet-dir
  - hostPath:
      path: /var/lib/kubelet/plugins/ebs.csi.aws.com/
      type: DirectoryOrCreate
    name: plugin-dir
  - hostPath:
      path: /var/lib/kubelet/plugins_registry/
      type: DirectoryOrCreate
    name: registration-dir
  - hostPath:
      path: /dev
      type: Directory
    name: device-dir
  - name: kube-api-access-n5zff
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace

```
