### ISSUE TITLE
Can we have opaque parameters in CSINode Object

### ISSUE THREAD

**Issue by humblec** [kubernetes-csi/node-driver-registrar#90]
Can we allow the CSINode object to be filled with some more parameters other than default known spec fields? for example: if I want to list the kernel version in this object, 

```
apiVersion: storage.k8s.io/v1
kind: CSINode
metadata:
  name: node1
spec:
  drivers:
  - name: mycsidriver.example.com
    nodeID: storageNodeID1
    topologyKeys: ['mycsidriver.example.com/regions', "mycsidriver.example.com/zones"]
```
